<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather</title>
    <link rel="icon" type="image/gif/png" href=<?php echo "../../../public/assets/images/titleimg.png"?> width="50" height="50" class="rounded mx-auto d-block" alt="icon">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <section class="">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-i tems-center">
                <?php $html = "";
                $id = str_replace("+", "-", $id);
                // error_reporting(0);
                $html .= '<div class="col col-md-1"> </div>
    
                <div class="col">
        <h1 class="display-5 fw-bolder">' . $response['location']['name'] . '</h1>
        <p class="lead">Region: ' . $response['location']['region'] . '</p>
        <p class="lead">Country: ' . $response['location']['country'] . '</p>
        <p class="lead">Current Timezone: ' . $response['location']['tz_id'] . '</p>
        <p class="lead">Local Time: ' . $response['location']['localtime'] . '</p>
    </div>
    <div class="col float-end">
    <h3 class="display-5 fw-bolder text-muted">Current Weather Conditions</h3>
    <p class="display-5 fw-bolder"><img src="' . $response['current']['condition']['icon'] . '" alt="icon">' . $response['current']['condition']['text'] . '</p>
    <p class="display-5 fw-bolder">Temperature: ' . $response['current']['temp_c'] . '&degC / ' . $response['current']['temp_f'] . ' F</p>
   <form action="/index/details?id=' . $this->request->get('id') . '&day=' . $response['current']['is_day'] . '" method="post">
    <input type="submit" class="btn btn-outline-info" name="currentweather" value="Current Weather">
    <input type="submit" class="btn btn-outline-success" name="forecast" value="Forecast"> 
    <input type="submit" class="btn btn-outline-dark" name="history" value="History"> 
    <input type="submit" class="btn btn-outline-secondary" name="timezone" value="Time Zone"><br><br> 
    <input type="submit" class="btn btn-outline-secondary" name="sports" value="Sports"> 
    <input type="submit" class="btn btn-outline-primary" name="astronomy" value="Astronomy"> 
    <input type="submit" class="btn btn-outline-danger" name="weatheralerts" value="Weather Alerts">
    <input type="submit" class="btn btn-outline-warning" name="aqi" value="Air Quality">
    </form>
    </div>';

                ?>
                <?php echo $html; ?>
            </div>
        </div>
        <div class="col" style="width:46%;float:right;">
            <?php if ($answer) {
                echo '<h3>'.$selected.'</h3><br>';
                foreach ($answer as $k => $v) {
                    echo '<b>'.$k.'</b>' . ': ' . $v . '<br>';
                }
            } ?>
        </div>

    </section>
</body>

</html>