<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <title>Weather</title>
</head>
<style>
    @media (min-width: 1025px) {
        .h-custom {
            height: 100vh !important;
        }
    }
</style>

<body>

    <section class="mt-5">
        <div class="container h-50">

            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-6">

                    <h3 class="mb-4 pb-2 pb-md-0 mb-md-3 px-md-2 float-center">Search Location</h3>
                    <form class="px-md-2" method="post" action="">

                        <div class="form-floating mb-3">
                            <input name="name" type="text" class="form-control" id="floatingInput" placeholder="Book Name">
                            <label for="floatingInput">Location</label>
                        </div>
                        <input type="submit" value="Get Locations" name="search" class="btn btn-success">
                </div>
                </form>

                <?php echo $count; ?>
            </div>
        </div>
        <?php

        // if ($count) {
        //     echo $count . '' . $title . '' . implode($author_name) . '' . $FPY;
        // }
        if ($NRF) {
            echo $NRF;
        }

        ?>
    </section>
    <?php
    error_reporting(0);
    // die($count);
    $html = '';
    foreach ($response as $value) {
        $html .= '<div class="border p-3 bg-dark text-light m-5">
         <div class="card-body">
          <p class="card-text"><h3>' . $value['name'] . '</h3></p>
          <p class="card-text">Region: ' . $value['region'] . '</p>
          <p class="card-text">Country: ' . $value['country'] . '</p>
          <p class="card-text">Latitude: ' . $value['lat'] . '</p>
          <p class="card-text">Longitude: ' . $value['lon'] . '</p>
          
          <a href="/index/details?id=' . $value['url'] . '" class="btn btn-primary">Details</a>
      </div>
      </div>';
    }
    echo $html;
    ?>





</body>

</html>